heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 5s


heartbeat.monitors:
- type: http
  id: frontend
  name: frontend
  service.name: frontend
  hosts: ["http://frontend:3000"]
  check.response.status: [200]
  schedule: '@every 30s'
- type: http
  id: backend
  name: backend
  service.name: backend
  hosts: ["http://backend:8090/getAllUpdates"]
  check.response.status: [200]
  schedule: '@every 30s'
- type: http
  id: keycloak
  name: keycloak
  service.name: keycloak
  hosts: ["http://keycloak:8080/auth"]
  check.response.status: [200]
  schedule: '@every 30s'

output.elasticsearch:
  hosts: ["es01:9200"]
  username: "elastic"
  password: "csit1234"
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/heartbeat/certs/ca/ca.crt"
  ssl.key: "/usr/share/heartbeat/certs/ca/ca.key"
  allow_older_versions: true
