FROM python:latest

RUN apt-get update && apt-get install -y inotify-tools
WORKDIR /setup 
COPY requirements.txt ./
COPY update_ip2l_ipv4.py ./
COPY update_ip2l_ipv6.py ./
COPY update_greynoise_ipv4.py ./
COPY update_greynoise_ipv6.py ./
COPY constants.py ./
COPY util.py ./
COPY setup.py ./
RUN pip install --user -r requirements.txt
COPY entrypoint.sh /
# WORKDIR /setup/GreynoiseIPv4 
# WORKDIR /setup/GreynoiseIPv6
# WORKDIR /setup/IP2L_IPv4
# WORKDIR /setup/IP2L_IPv6
# WORKDIR /setup
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
# CMD ["python","setup.py"]



