
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

# setup.dashboards.enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["es01:9200"]
  username: "elastic"
  password: "csit1234"
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/metricbeat/certs/ca/ca.crt"
  ssl.key: "/usr/share/metricbeat/certs/ca/ca.key"
  allow_older_versions: true

setup.kibana:
  host: "kibana:5601"
  protocol: "http"
  # ssl.enabled: true
  # ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
  # ssl.certificate: "/usr/share/metricbeat/certs/ca/ca.crt"
  # ssl.key: "/usr/share/metricbeat/certs/ca/ca.key"

