FROM eclipse-temurin:19-jdk-focal

# COPY certs/* /tmp/cacerts/
# RUN keytool -noprompt -import -trustcacerts -alias mdecert -file /usr/share/elasticsearch/config/certs/ca/ca.crt -keystore cacerts -keypass changeit -storepass changeit
WORKDIR "/opt/java/openjdk/lib/security"
COPY ca.crt ./ 
RUN keytool -noprompt -import -trustcacerts -alias mdecert -file ca.crt -keystore cacerts -keypass changeit -storepass changeit

WORKDIR "/backend"
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src
RUN ./mvnw dependency:go-offline

CMD ["./mvnw", "spring-boot:run"]
